package typst-community:subsetter@1.0.0+0.1.1;

interface types {
  resource profile {
    pdf: static func(glyphs: list<u16>) -> profile;
  }

  record tag {
    tuple0: tuple<u8, u8, u8, u8>,
  }

  variant error {
    unknown-kind,
    invalid-offset,
    missing-data,
    invalid-data,
    missing-table(tag),
  }
}

world subsetter {
  export types;
  use types.{profile, tag, error};

  export subset: func(data: list<u8>, index: u32, profile: profile) -> result<list<u8>, error>;
}
